#! /usr/bin/env bash

# run sed $'s/\r$//' ./docker-commands.sh > ./docker-commands.Unix.sh to convert windows \r\n endings to \n

# Define variables
IMAGE_NAME="k8s-controller"
VERSION="latest"
TAG="$IMAGE_NAME:$VERSION"

# Build the Docker image
docker build -t $TAG .

# Optionally, tag the image for a registry
REGISTRY="localhost:5000"
docker tag $TAG $REGISTRY/$TAG

echo "Docker Image built and tagged successfully!"

docker push $REGISTRY/$TAG

echo "Docker image pushed"